# Generated by Django 3.2.4 on 2021-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名')),
                ('password', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='密码')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '登录用户',
                'verbose_name_plural': '登录用户',
            },
        ),
        migrations.CreateModel(
            name='networkAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceNumber', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='设备编号')),
                ('ip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='IP')),
                ('mip', models.GenericIPAddressField(blank=True, default='', null=True, verbose_name='管理IP')),
                ('device_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='设备类型')),
                ('prot', models.IntegerField(blank=True, default=22, null=True, verbose_name='端口')),
                ('address', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='物理位置')),
                ('logicAddress', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='逻辑位置')),
                ('dState', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='设备状态')),
                ('islogin', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='连接状态')),
                ('principal', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='负责人')),
                ('desc', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='描述')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
            },
        ),
    ]
