# Generated by Django 3.2.4 on 2021-06-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_prot_networkassets_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='orgAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='菜单名称')),
                ('desc', models.TextField(blank=True, default='', max_length=50000, verbose_name='描述')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lastTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('creator', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='创建者')),
                ('editor', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='修改者')),
                ('parent', models.ForeignKey(blank=True, help_text='null表示不是菜单，否则为二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.orgassets', verbose_name='所属一级菜单')),
            ],
            options={
                'verbose_name': '资产组织架构',
                'verbose_name_plural': '资产组织架构',
            },
        ),
    ]
