# Generated by Django 3.2.4 on 2021-06-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_orgassets'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgassets',
            name='sort',
            field=models.IntegerField(default=1, verbose_name='显示顺序'),
        ),
    ]
