# Generated by Django 3.2.4 on 2021-06-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orgassets_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgassets',
            old_name='name',
            new_name='title',
        ),
    ]
